# Generated by Django 4.2.11 on 2025-11-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('preferred_visualization', models.CharField(default='mood_blob', max_length=20)),
                ('enable_weekly_summaries', models.BooleanField(default=True)),
                ('enable_future_letters', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='MoodVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('mood_blob', 'Mood Blob'), ('emotion_chart', 'Emotion Chart'), ('timeline', 'Timeline'), ('heatmap', 'Heatmap'), ('word_cloud', 'Word Cloud')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='visualizations/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Visualization',
                'verbose_name_plural': 'Mood Visualizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Write your thoughts here...')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral'), ('love', 'Love'), ('anxiety', 'Anxiety'), ('excitement', 'Excitement')], max_length=20)),
                ('primary_emotion_score', models.FloatField(help_text='Confidence score 0-1')),
                ('joy_score', models.FloatField(default=0.0)),
                ('sadness_score', models.FloatField(default=0.0)),
                ('anger_score', models.FloatField(default=0.0)),
                ('fear_score', models.FloatField(default=0.0)),
                ('surprise_score', models.FloatField(default=0.0)),
                ('disgust_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('love_score', models.FloatField(default=0.0)),
                ('anxiety_score', models.FloatField(default=0.0)),
                ('excitement_score', models.FloatField(default=0.0)),
                ('sentiment_polarity', models.FloatField(help_text='Range from -1 (negative) to 1 (positive)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_analysis', to='journal.journalentry')),
            ],
            options={
                'verbose_name': 'Emotion Analysis',
                'verbose_name_plural': 'Emotion Analyses',
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('weekly_summary', 'Weekly Summary'), ('future_letter', 'Letter to Future Self'), ('pattern_analysis', 'Pattern Analysis'), ('recommendation', 'Recommendation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('related_entries', models.ManyToManyField(related_name='insights', to='journal.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-created_at'], name='journal_jou_created_b6c001_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-created_at'], name='journal_jou_user_id_1ad335_idx'),
        ),
    ]
